### ISSUE TITLE
Should we keep this repository ?

### ISSUE THREAD

**Issue by funilrys** [dead-hosts/AdBlockID_git_realodix#6]
Hey @realodix, 

as I'm migrating to a new infrastructure (see: https://github.com/orgs/dead-hosts/discussions/1), it came to my attention that the URL that is given doesn't exist anymore (404). 

So my question: Do you want to migrate to the new infrastructure, or should I delete this repository ?

Or do you need a new repository?

Cheers, 
Nissar

**Comment by realodix** [comment]
> Do you want to migrate to the new infrastructure, or should I delete this repository ?
> Or do you need a new repository?

Halo @funilrys

I have now updated the `raw_link` in the info.json file. Yes, I want to migrate to the new infrastructure.

**Comment by funilrys** [comment]
✔️
